image: docker:latest

variables:
    CI_APP_IMAGE_WITH_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    CI_NGINX_IMAGE_WITH_TAG: "$CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_REF_NAME"

stages:
  - deps
  - test
  - build
  - deploy

.template-suffix-vars: &suffix-vars
    before_script:
      - cat .env | grep ENV_ > .build-env
      - sed -i 's/^/export /' .build-env
      - for name in `env | awk -F= '{if($1 ~ /'"$ENV_SUFFIX"'$/) print $1}'`; do
          echo 'export '`echo $name|awk -F''"$ENV_SUFFIX"'$' '{print $1}'`'='`printenv $name`'' >> .build-env;
        done

.template-docker-nginx-image: &docker-nginx-image
    stage: build
    image: docker:latest
    <<: *suffix-vars
    script:
      - eval $(cat .build-env)
      - docker build --tag $CI_NGINX_IMAGE_WITH_TAG --build-arg server_name=$SERVER_NAME --build-arg server_upstream=prod --build-arg app_php=app ./docker/nginx
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker push $CI_NGINX_IMAGE_WITH_TAG
      - docker logout $CI_REGISTRY
    tags:
      - executor-docker
      - docker-in-docker

.template-docker-app-image: &docker-app-image
    stage: build
    image: docker:latest
    <<: *suffix-vars
    script:
      - eval $(cat .build-env)
      - echo '{"github-oauth":{"github.com":"'"$COMPOSER_GITHUB_TOKEN"'"}}' > ./auth.json
      - docker build --tag $CI_APP_IMAGE_WITH_TAG .
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker push $CI_APP_IMAGE_WITH_TAG
      - docker logout $CI_REGISTRY
    tags:
      - executor-docker
      - docker-in-docker

.template-docker-compose: &docker-compose
    stage: build
    image: covex/docker-compose:1.0
    <<: *suffix-vars
    script:
      - eval $(cat .build-env)
      - mkdir build
      - docker-compose -f docker-compose-deploy.yml config > build/docker-compose.yml
      - sed -i 's/\/builds\/'"$CI_PROJECT_NAMESPACE"'\/'"$CI_PROJECT_NAME"'/\./g' build/docker-compose.yml
    artifacts:
        untracked: true
        name: "$CI_COMMIT_REF_NAME"
        paths:
          - build/
    tags:
      - executor-docker
    dependencies: []

.template-secure-copy: &secure-copy
    stage: deploy
    image: covex/alpine-git:1.0
    <<: *suffix-vars
    script:
      - eval $(cat .build-env)
      - eval $(ssh-agent -s)
      - ssh-add <(echo "$SSH_PRIVATE_KEY")
      - ssh -p 22 $DEPLOY_USER@$DEPLOY_HOST 'set -e ;
          rm -rf '"$DEPLOY_DIRECTORY"'_tmp ;
          mkdir -p '"$DEPLOY_DIRECTORY"'_tmp'
      - scp -P 22 -r build/* ''"$DEPLOY_USER"'@'"$DEPLOY_HOST"':'"$DEPLOY_DIRECTORY"'_tmp'
      - ssh -p 22 $DEPLOY_USER@$DEPLOY_HOST 'set -e ;
          if [ -d '"$DEPLOY_DIRECTORY"' ]; then rm -rf '"$DEPLOY_DIRECTORY"'; fi ;
          mv '"$DEPLOY_DIRECTORY"'_tmp '"$DEPLOY_DIRECTORY"' ;
          cd '"$DEPLOY_DIRECTORY"' ;
          docker login -u gitlab-ci-token -p '"$CI_JOB_TOKEN"' '"$CI_REGISTRY"' ;
          docker-compose pull ;
          docker-compose up -d --no-recreate ;
          docker-compose up -d --force-recreate --no-deps spare ;
          docker-compose exec -T spare sh -c "cd /srv && rm -rf b/* && cp -a web/. b/ && rm -rf a/* && cp -a web/. a/" ;
          docker-compose exec -T spare phing storage-prepare database-deploy ;
          docker-compose up -d --force-recreate --no-deps php'
      - ssh -p 22 $DEPLOY_USER@$DEPLOY_HOST 'set -e ;
          cd '"$DEPLOY_DIRECTORY"' ;
          echo "[$(date -R)] web-server is down" ;
          docker-compose stop nginx ;
          docker-compose up -d nginx ;
          echo "[$(date -R)] web-server is up"'
    tags:
      - executor-docker

deps:php-composer:
    stage: deps
    image: covex/php7.1-fpm:1.0
    script:
      - echo '{"github-oauth":{"github.com":"'"$COMPOSER_GITHUB_TOKEN"'"}}' > ./auth.json
      - composer install --prefer-dist --no-scripts --no-autoloader --no-interaction
    tags:
      - executor-docker

test:phpunit:
    stage: test
    image: covex/php7.1-fpm:1.0
    <<: *suffix-vars
    variables:
        ENV_SUFFIX: "_TEST"
    script:
      - eval $(cat .build-env)
      - echo '{"github-oauth":{"github.com":"'"$COMPOSER_GITHUB_TOKEN"'"}}' > ./auth.json
      - composer require phpunit/phpunit:* --dev
      - phpunit
    tags:
      - executor-docker

build:docker-nginx-image-master:
    <<: *docker-nginx-image
    variables:
        ENV_SUFFIX: "_MASTER"
    only:
      - master
    except:
      - tags

build:docker-nginx-image-production:
    <<: *docker-nginx-image
    variables:
        ENV_SUFFIX: "_PRODUCTION"
    only:
      - /^release-.*$/
    except:
      - branches

build:docker-app-image-master:
    <<: *docker-app-image
    variables:
        ENV_SUFFIX: "_MASTER"
    only:
      - master
    except:
      - tags

build:docker-app-image-production:
    <<: *docker-app-image
    variables:
        ENV_SUFFIX: "_PRODUCTION"
    only:
      - /^release-.*$/
    except:
      - branches

build:docker-compose-master:
    <<: *docker-compose
    variables:
        ENV_SUFFIX: "_MASTER"
    only:
      - master
    except:
      - tags

build:docker-compose-production:
    <<: *docker-compose
    variables:
        ENV_SUFFIX: "_PRODUCTION"
    only:
      - /^release-.*$/
    except:
      - branches

deploy:secure-copy-master:
    variables:
        ENV_SUFFIX: "_MASTER"
    <<: *secure-copy
    only:
      - master
    except:
      - tags
    environment:
        name: staging
    dependencies:
      - build:docker-compose-master

deploy:secure-copy-production:
    variables:
        ENV_SUFFIX: "_PRODUCTION"
    <<: *secure-copy
    only:
      - /^release-.*$/
    except:
      - branches
    environment:
        name: production
    dependencies:
      - build:docker-compose-production

deploy:sync-project-forks:
    stage: deploy
    image: covex/alpine-git:1.0
    before_script:
      - eval $(ssh-agent -s)
      - ssh-add <(echo "$SSH_PRIVATE_KEY")
    script:
      - git branch -d stable || true
      - git checkout -b stable
      - for FORK in $PROJECT_FORKS; do git remote add fork $FORK && git push fork stable && git remote rm fork; done
    only:
      - master
    dependencies: []
    tags:
      - executor-docker
