version: '3.4'

services:
    mysql:
        ports:
            - "3306:3306"
        networks:
          - nw_internal

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
          - 8080:80
        networks:
          - nw_internal
        environment:
            PMA_ARBITRARY: "1"
            PMA_HOST: "mysql"
            PMA_USER: "root"
            PMA_PASSWORD: "${ENV_database_root_password}"
        depends_on:
          - mysql
        volumes:
          - /sessions

networks:
    nw_internal:
