version: "2.1"

services:
    nginx:
        image: "${CI_NGINX_IMAGE_WITH_TAG}"
        ports:
          - "80"
        restart: always
        networks:
            nw_internal:
            nw_external:
                ipv4_address: ${NETWORK_IP}
#                link_local_ips:
#                  - ${NETWORK_IP}
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
          - "assets:/srv/a:ro"
          - "assets:/srv/b:ro"
          - "assets:/srv/storage:ro"

    php:
        extends:
            file: docker-common.yml
            service: php
        image: "${CI_APP_IMAGE_WITH_TAG}"
        networks:
          - nw_internal
        restart: always
        volumes:
          - "assets:/srv/a:rw"
          - "assets:/srv/storage:rw"

    spare:
        extends:
            file: docker-common.yml
            service: php
        image: "${CI_APP_IMAGE_WITH_TAG}"
        networks:
          - nw_internal
        volumes:
          - "assets:/srv/b:rw"
          - "assets:/srv/storage:rw"

    mysql:
        extends:
            file: docker-common.yml
            service: mysql
        restart: always
        networks:
          - nw_internal

volumes:
    database:
    assets:

networks:
    nw_external:
        external:
            name: ${NETWORK_NAME}
    nw_internal:
