version: "2.1"

services:
    nginx:
        build:
          context: ./docker/nginx/
          args:
            server_name: "${SERVER_NAME}"
            app_php: "${APP_PHP}"
        ports:
          - "${NGINX_PORTS}"
        restart: always
        networks:
            nw_internal:
            nw_external:
                ipv4_address: ${NETWORK_IP}
#                link_local_ips:
#                  - ${NETWORK_IP}
        depends_on:
          - php
        volumes_from:
          - "php:ro"

    php:
        extends:
            file: docker-common.yml
            service: php
        image: "${APNET_REGISTRY_IMAGE_TAG}"
        expose:
          - 9000
        networks:
          - nw_internal
        restart: always
        depends_on:
          - mysql
        volumes:
          - "/srv"

    mysql:
        extends:
            file: docker-common.yml
            service: mysql
        networks:
          - nw_internal

volumes:
    database:

networks:
    nw_external:
        external:
            name: ${NETWORK_NAME}
    nw_internal:
